In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image

In [31]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv("./dataset/dataset/DecisionTree_PastHires.csv")

In [4]:
df

Years Experience Employed?  Previous employers Level of Education  \
0                 10         Y                   4                 BS   
1                  0         N                   0                 BS   
2                  7         N                   6                 BS   
3                  2         Y                   1                 MS   
4                 20         N                   2                PhD   
5                  0         N                   0                PhD   
6                  5         Y                   2                 MS   
7                  3         N                   1                 BS   
8                 15         Y                   5                 BS   
9                  0         N                   0                 BS   
10                 1         N                   1                PhD   
11                 4         Y                   1                 BS   
12                 0         N                   0                PhD   

   Top-tier school Interned Hired  
0                N        N     Y  
1                Y        Y     Y  
2                N        N     N  
3                Y        N     Y  
4                Y        N     N  
5                Y        Y     Y  
6                N        Y     Y  
7                N        Y     Y  
8                N        N     Y  
9                N        N     N  
10               Y        N     N  
11               N        Y     Y  
12               Y        N     Y

In [6]:
df.keys()

Index(['Years Experience', 'Employed?', 'Previous employers',
       'Level of Education', 'Top-tier school', 'Interned', 'Hired'],
      dtype='object')

In [10]:
df['Level of Education'].value_counts()

Level of Education
BS     7
PhD    4
MS     2
Name: count, dtype: int64

In [11]:
d1={'Y':1,'N':0}
d2={'BS':1,'MS':2,'PhD':3}

In [12]:
df['Employed?']=df['Employed?'].map(d1)
df['Top-tier school']=df['Top-tier school'].map(d1)
df['Interned']=df['Interned'].map(d1)

In [13]:
df['Level of Education']=df['Level of Education'].map(d2)
df['Hired']=df['Hired'].map(d1)

In [14]:
df

Years Experience  Employed?  Previous employers  Level of Education  \
0                 10          1                   4                   1   
1                  0          0                   0                   1   
2                  7          0                   6                   1   
3                  2          1                   1                   2   
4                 20          0                   2                   3   
5                  0          0                   0                   3   
6                  5          1                   2                   2   
7                  3          0                   1                   1   
8                 15          1                   5                   1   
9                  0          0                   0                   1   
10                 1          0                   1                   3   
11                 4          1                   1                   1   
12                 0          0                   0                   3   

    Top-tier school  Interned  Hired  
0                 0         0      1  
1                 1         1      1  
2                 0         0      0  
3                 1         0      1  
4                 1         0      0  
5                 1         1      1  
6                 0         1      1  
7                 0         1      1  
8                 0         0      1  
9                 0         0      0  
10                1         0      0  
11                0         1      1  
12                1         0      1

In [33]:
model=DecisionTreeClassifier(criterion='gini',random_state=42)
model2=RandomForestClassifier(n_estimators=100, random_state=2)

In [24]:
X=df.iloc[:, :-1].values
print(X)
Y=df.iloc[:, -1].values
print(Y)
X_train,X_test,Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)

[[10  1  4  1  0  0]
 [ 0  0  0  1  1  1]
 [ 7  0  6  1  0  0]
 [ 2  1  1  2  1  0]
 [20  0  2  3  1  0]
 [ 0  0  0  3  1  1]
 [ 5  1  2  2  0  1]
 [ 3  0  1  1  0  1]
 [15  1  5  1  0  0]
 [ 0  0  0  1  0  0]
 [ 1  0  1  3  1  0]
 [ 4  1  1  1  0  1]
 [ 0  0  0  3  1  0]]
[1 1 0 1 0 1 1 1 1 0 0 1 1]


In [34]:
model.fit(X_train,Y_train)
model2.fit(X_train,Y_train)
y_pred=model.predict(X_test)
y_pred2=model2.predict(X_test)

In [35]:
print("precision", metrics.accuracy_score(Y_test, y_pred))

precision 0.6666666666666666


In [36]:
print("precision", metrics.accuracy_score(Y_test, y_pred2))

precision 0.6666666666666666
